using static CoRPatternDependencies.AbstractClasses;
using static CoRPatternDependencies.Classes;

namespace MightyGumballEmailClassifier
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Handler spamHandler = new SpamHandler();
            Handler fanHandler = new FanHandler();
            Handler complaintHandler = new ComplaintHandler();
            Handler newLocHandler = new NewLocHandler();

            spamHandler.SetSuccessor(fanHandler);
            fanHandler.SetSuccessor(complaintHandler);
            complaintHandler.SetSuccessor(newLocHandler);

            /********************* Sample emails generated by CoPilot *********************/

            Email e1 = new("Fan", "We love the 1-in-10 game!");
            Email e2 = new("Complaint", "My kid is addicted to gambling now.");
            Email e3 = new("Spam", "Buy cheap gumballs now!");
            Email e4 = new("NewLoc", "Please put a machine in our breakroom.");
            Email e5 = new("Unknown", "Just saying hello.");

            /************************************************************************************/

            Console.WriteLine("\nThe Mighty Gumball Email Classifier - \n");
            spamHandler.HandleRequest(e1);
            spamHandler.HandleRequest(e2);
            spamHandler.HandleRequest(e3);
            spamHandler.HandleRequest(e4);
            spamHandler.HandleRequest(e5);
        }
    }
}
